[workflow]
dataset = "rgptest"
ar-guid = "standalone"


[cohorts.rgptest]
description = "RGP cohort"

[cohorts.rgptest.genome]
description = ""
seqr_lookup = ""
external_labels = ""
seqr_instance = ""
seqr_project = ""

