[buckets]
web_suffix = 'web'
tmp_suffix = 'tmp'
analysis_suffix = 'analysis'

[storage.rgptest]
default = "https://kahlquisrefsa.blob.core.windows.net/test"
web = "https://kahlquisrefsa.blob.core.windows.net/test-web"
analysis = "https://kahlquisrefsa.blob.core.windows.net/test-analysis"
tmp = "https://kahlquisrefsa.blob.core.windows.net/test-tmp"

[storage.common]
analysis = "https://kahlquisrefsa.blob.core.windows.net/test/common/analysis"
tmp = "https://kahlquisrefsa.blob.core.windows.net/test-tmp"

[workflow]
name = 'AIP'
scatter_count = 100
vcf_size_in_gb = 300  # if the input is a VCF, specify enough storage to fit it
sequencing_type = 'genome'
presentation = 'cpg'

# where to register outputs, if at all
#register = 'metamist'

## override clinvar results
#clinvar_decisions = "HailTable path to private ClinVar"
#clinvar_pm5 = "HailTable path to ClinVar PM5"

## optionally, ignore some categories
#ignore_categories = [
#    'categoryboolean6'
#]

[panels]
default_panel = 137
panelapp = 'https://panelapp.agha.umccr.org/api/v1/panels'
panel_month_delta = 12
require_pheno_match = ['FLG', 'GJB2', 'F2', 'F5']

[clinvar]
filter_benign = ['illumina laboratory services; illumina']

[moi_tests]
# thresholds for different filters during the MOI checks
gnomad_dominant = 0.001
gnomad_max_homs_dominant = 0
gnomad_max_homs_recessive = 1
gnomad_max_ac_dominant = 10
gnomad_max_hemi = 1
callset_af_sv_dominant = 0.01

[csq]
# variables affecting how the VCF variants are parsed, and AnalysisVariant objects are populated
csq_string = ['allele', 'consequence', 'symbol', 'gene', 'feature', 'mane_select', 'biotype', 'exon', 'hgvsc', 'hgvsp', 'cdna_position', 'cds_position', 'amino_acids', 'protein_position', 'variant_class', 'ensp', 'lof', 'sift', 'polyphen', 'am_class', 'am_pathogenicity']

[filter]
# variables for the hail operations, including CSQ sets and filter thresholds
ac_threshold = 0.01
additional_csq = ['missense_variant']
af_semi_rare = 0.01
cadd = 28.1
callset_af_sv_recessive = 0.03
critical_csq = ['frameshift_variant', 'splice_acceptor_variant', 'splice_donor_variant', 'start_lost', 'stop_gained', 'stop_lost', 'transcript_ablation']
gerp = 1.0
eigen = 0.25
max_parent_ab = 0.05
minimum_depth = 10
polyphen = 0.99
revel = 0.77
sift = 0.0
spliceai = 0.5

[categories]
1 = 'ClinVar Pathogenic'
2 = 'New Gene-Disease Association'
3 = 'High Impact Variant'
4 = 'de Novo'
5 = 'High SpliceAI Score'
6 = 'AlphaMissense P/LP'
pm5 = 'ACMG PM5 - missense in same residue as known pathogenic'
support = 'High in Silico Scores'
sv1 = 'Predicted LOF SV'

[hail]
cancel_after_n_failures = 1
default_timeout = 12000
default_memory = 'highmem'
billing_project = 'best-kahlquis'

[references]
genome_build = "GRCh38"
vep_110_mount = "https://kahlquisref.blob.core.windows.net/reference/vep/110.1/mount"
seqr_combined_reference_data = "https://kahlquisref.blob.core.windows.net/reference/seqr/v0-1/combined_reference_data_grch38.ht"
seqr_clinvar = "https://kahlquisref.blob.core.windows.net/reference/seqr/v0-1/clinvar.GRCh38.ht"

[images]
cpg_workflows = "kahlquisaipcr.azurecr.io/cpg-common/images/cpg_workflows:latest"
bcftools = "kahlquisaipcr.azurecr.io/cpg-common/images/bcftools:1.16"
gatk = "kahlquisaipcr.azurecr.io/cpg-common/images/gatk:4.2.6.1"
picard = "kahlquisaipcr.azurecr.io/cpg-common/images/picard:2.27.4"
samtools = "kahlquisaipcr.azurecr.io/cpg-common/images/samtools:1.16.1"
vep = "kahlquisaipcr.azurecr.io/cpg-common/images/vep:105.0"
cpg_aip = "kahlquisaipcr.azurecr.io/cpg-common/images/cpg_aip:miah"

# per-cohort section
#clinvar_filter = when running a clinvar re-summary, remove submissions by these sites. Default = no removal
#cohort_panels = any panel IDs to be applied to this cohort, even if not otherwise phenotype-matched
#cohort_percentage = when generating an analysis pedigree, reduce the cohort to this percentage of the total. Default = 100
#gene_prior = if a specific gene list is to be used to determine Cat 2 (new gene-disease associations), provide the filepath here
