[dataset_specific]
description = "variables affecting how the final HTML report appears"
external_lookup = ""
forbidden = ""
external_labels = ""

seqr_instance = "http://seqr.broadinstitute.org"
seqr_project = "R0384_rare_genomes_project_gen"
seqr_lookup = ""
