[buckets]
web_suffix = 'web'
tmp_suffix = 'tmp'
analysis_suffix = 'analysis'

[workflow]
name = 'AIP'
scatter_count = 100
vcf_size_in_gb = 18  # if the input is a VCF, specify enough storage to fit it
sequencing_type = 'genome'
default_panel = 137
panelapp = 'https://panelapp.agha.umccr.org/api/v1/panels'
panel_month_delta = 12

[clinvar]
filter_all = ['victorian clinical genetics services,murdoch childrens research institute', 'broad institute rare disease group; broad institute', 'laboratory for molecular medicine; mass general brigham personalized medicine']
filter_benign = ['illumina laboratory services; illumina']

[moi_tests]
description = 'thresholds for different filters during the MOI checks'
gnomad_dominant = 0.001
gnomad_max_homs_dominant = 0
gnomad_max_homs_recessive = 1
gnomad_max_ac_dominant = 10
gnomad_max_hemi = 1

[csq]
description = 'variables affecting how the VCF variants are parsed, and AnalysisVariant objects are populated'
csq_string = ['consequence', 'symbol', 'gene', 'feature', 'mane_select', 'biotype', 'exon', 'hgvsc', 'hgvsp', 'variant_class', 'ensp', 'lof']

[filter]
description = 'variables for the hail operations, including CSQ sets and filter thresholds'
ac_threshold = 0.01
additional_csq = ['missense_variant']
af_semi_rare = 0.01
cadd = 28.1
critical_csq = ['frameshift_variant', 'splice_acceptor_variant', 'splice_donor_variant', 'start_lost', 'stop_gained', 'stop_lost', 'transcript_ablation']
gerp = 1.0
eigen = 0.25
lenient_de_novo = false
minimum_depth = 10
polyphen = 0.99
revel = 0.77
sift = 0.0
spliceai = 0.5

[hail]
cancel_after_n_failures = 1
default_timeout = 6000
default_memory = 'highmem'

[references.broad]
dragmap_prefix = "hail-az://azcpg001sa/reference/hg38/v0/dragen_reference"
ref_fasta = "hail-az://azcpg001sa/reference/hg38/v0/dragen_reference/Homo_sapiens_assembly38_masked.fasta"
genome_calling_interval_lists = "hail-az://azcpg001sa/reference/hg38/v0/wgs_calling_regions.hg38.interval_list"

[references]
genome_build = "GRCh38"
vep_mount = "hail-az://azcpg001sa/reference/vep/105.0/mount"
seqr_combined_reference_data = "hail-az://azcpg001sa/reference/seqr/v0-1/combined_reference_data_grch38.ht"
seqr_clinvar = "hail-az://azcpg001sa/reference/seqr/v0-1/clinvar.GRCh38.ht"

[images]
cpg_workflows = "azcpg001acr.azurecr.io/cpg-common/images/cpg_workflows:latest"
bcftools = "azcpg001acr.azurecr.io/cpg-common/images/bcftools:1.16"
gatk = "azcpg001acr.azurecr.io/cpg-common/images/gatk:4.2.6.1"
picard = "azcpg001acr.azurecr.io/cpg-common/images/picard:2.27.4"
samtools = "azcpg001acr.azurecr.io/cpg-common/images/samtools:1.16.1"
vep = "azcpg001acr.azurecr.io/cpg-common/images/vep:105.0"

[dataset_specific]
description = 'placeholder for per-cohort data'
require_pheno_match = ['FLG']
