[buckets]
web_suffix = 'web'
tmp_suffix = 'tmp'
analysis_suffix = 'analysis'

[workflow]
name = 'AIP'
scatter_count = 20
vcf_size_in_gb = 2  # if the input is a VCF, specify enough storage to fit it
sequencing_type = 'genome'

[panels]
default_panel = 137
panelapp = 'https://panelapp.agha.umccr.org/api/v1/panels'
panel_month_delta = 12
require_pheno_match = ['FLG', 'GJB2']

[clinvar]
filter_benign = ['illumina laboratory services; illumina']

[moi_tests]
# thresholds for different filters during the MOI checks
gnomad_dominant = 0.001
gnomad_max_homs_dominant = 0
gnomad_max_homs_recessive = 1
gnomad_max_ac_dominant = 10
gnomad_max_hemi = 1

[csq]
# variables affecting how the VCF variants are parsed, and AnalysisVariant objects are populated
csq_string = ['consequence', 'symbol', 'gene', 'feature', 'mane_select', 'biotype', 'exon', 'hgvsc', 'hgvsp', 'variant_class', 'ensp', 'lof']

[filter]
# variables for the hail operations, including CSQ sets and filter thresholds
ac_threshold = 0.01
additional_csq = ['missense_variant']
af_semi_rare = 0.01
cadd = 28.1
codon_table = "gs://cpg-common-test/clinvar/codon_indexed.ht"
critical_csq = ['frameshift_variant', 'splice_acceptor_variant', 'splice_donor_variant', 'start_lost', 'stop_gained', 'stop_lost', 'transcript_ablation']
gerp = 1.0
eigen = 0.25
lenient_de_novo = true
minimum_depth = 10
polyphen = 0.99
revel = 0.77
sift = 0.0
spliceai = 0.5


[hail]
cancel_after_n_failures = 1
default_timeout = 6000
default_memory = 'highmem'
billing_project = 'miah-trial'

[references.broad]
dragmap_prefix = "hail-az://kaileighref/reference/hg38/v0/dragen_reference"
ref_fasta = "hail-az://kaileighref/reference/hg38/v0/dragen_reference/Homo_sapiens_assembly38_masked.fasta"
genome_calling_interval_lists = "hail-az://kaileighref/reference/hg38/v0/wgs_calling_regions.hg38.interval_list"

[references]
genome_build = "GRCh38"
vep_mount = "hail-az://kaileighref/reference/vep/105.0/mount"
seqr_combined_reference_data = "hail-az://kaileighref/reference/seqr/v0-1/combined_reference_data_grch38.ht"
seqr_clinvar = "hail-az://kaileighref/reference/seqr/v0-1/clinvar.GRCh38.ht"

[images]
cpg_workflows = "kaileighacr.azurecr.io/cpg-common/images/cpg_workflows:latest"
bcftools = "kaileighacr.azurecr.io/cpg-common/images/bcftools:1.16"
gatk = "kaileighacr.azurecr.io/cpg-common/images/gatk:4.2.6.1"
picard = "kaileighacr.azurecr.io/cpg-common/images/picard:2.27.4"
samtools = "kaileighacr.azurecr.io/cpg-common/images/samtools:1.16.1"
vep = "kaileighacr.azurecr.io/cpg-common/images/vep:105.0"

# per-cohort section
#clinvar_filter = when running a clinvar re-summary, remove submissions by these sites. Default = no removal
#cohort_panels = any panel IDs to be applied to this cohort, even if not otherwise phenotype-matched
#cohort_percentage = when generating an analysis pedigree, reduce the cohort to this percentage of the total. Default = 100
#gene_prior = if a specific gene list is to be used to determine Cat 2 (new gene-disease associations), provide the filepath here

[cohorts.acute-care]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
#cohort_percentage = 80
gene_prior = 'gs://cpg-acute-care-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.ag-hidden]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
gene_prior = 'gs://cpg-ag-hidden-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.brain-malf]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
#cohort_percentage = 80
gene_prior = 'gs://cpg-brain-malf-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.broad-rgp]
clinvar_filter = [
    'broad institute rare disease group; broad institute',
    'laboratory for molecular medicine; mass general brigham personalized medicine'
]
gene_prior = "gs://cpg-broad-rgp-test-analysis/reanalysis/jan_2020_panels.json"

[cohorts.circa]
#cohort_percentage = 80

[cohorts.epileptic-enceph]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
#cohort_percentage = 80
gene_prior = 'gs://cpg-epileptic-enceph-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.heartkids]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
gene_prior = 'gs://cpg-heartkids-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.hereditary-neuro]
#cohort_percentage = 80

[cohorts.ibmdx]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']

[cohorts.kidgen]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
gene_prior = 'gs://cpg-kidgen-test-analysis/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.leukodystrophies]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
cohort_panels = [298, 299, 3094]
#cohort_percentage = 80
gene_prior = 'gs://cpg-leukodystrophies-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.mito-disease]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
#cohort_percentage = 80
gene_prior = 'gs://cpg-mito-disease-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.ohmr3-mendelian]

[cohorts.ohmr4-epilepsy]

[cohorts.perth-neuro]

[cohorts.ravenscroft-arch]

[cohorts.ravenscroft-rdstudy]

[cohorts.rdnow]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
gene_prior = 'gs://cpg-rdnow-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.schr-neuro]

[cohorts.udn-aus]
