[dataset_specific]
description = "variables affecting how the final HTML report appears"
seqr_lookup = ""
external_lookup = ""
seqr_instance = "https://this.is.a/placeholder"
seqr_project = "placeholder"
forbidden = ""

[workflow]
sequencing_type = "genome"

[images]
hail = "hail-driver:latest"
vep = "vep:105.0"

[references]
genome_build = 'GRCh38'
vep_mount = "vep/105.0"