[dataset_specific]
description = "variables affecting how the final HTML report appears"
seqr_lookup = ""
external_lookup = ""
seqr_instance = "https://this.is.a/placeholder"
seqr_project = "placeholder"
forbidden = ""

[workflow]
sequencing_type = "genome"

[images]
hail = "hail-driver:latest"
vep = "vep:105.0"
gatk = "gatk:4.2.6.1"
bcftools = "bcftools:1.16"
bwa = "bwa:v0"
bwamem2 = "bwamem2:v0"
dragmap = "dragmap:1.3.0"
samtools = "picard_samtools:v0"
picard = "picard_samtools:v0"
picard_samtools = "picard_samtools:v0"
somalier = "somalier:v0.2.15"
peddy = "peddy:v0"
verifybamid = "verifybamid:2.0.1"
multiqc = "multiqc:v1.12"
fastqc = "fastqc:v0.11.9_cv8"
cpg_workflows = "cpg_workflows:latest"


[references]
genome_build = 'GRCh38'
vep_mount = "vep/105.0"

[references.seqr]
prefix = 'seqr/v0-1'
combined_reference = 'seqr/v0-1/combined_reference_data_grch38.ht'
clinvar = 'seqr/v0-1/clinvar.GRCh38.ht'

[references.broad]
prefix = "hg38/v0"
dragmap_prefix = "dragen_reference"
ref_fasta = "hg38/v0/dragen_reference/Homo_sapiens_assembly38_masked.fasta"
noalt_bed = "sv-resources/resources/v1/primary_contigs_plus_mito.bed.gz"
exome_bed = "Homo_sapiens_assembly38.contam.exome_calling_regions.v1.bed"
genome_calling_interval_lists = "wgs_calling_regions.hg38.interval_list"
exome_calling_interval_lists = "exome_calling_regions.v1.interval_list"
genome_evaluation_interval_lists = "wgs_evaluation_regions.hg38.interval_list"
exome_evaluation_interval_lists = "exome_evaluation_regions.v1.interval_list"
genome_coverage_interval_list = "wgs_coverage_regions.hg38.interval_list"
dbsnp_vcf = "Homo_sapiens_assembly38.dbsnp138.vcf"
dbsnp_vcf_index = "Homo_sapiens_assembly38.dbsnp138.vcf.idx"
hapmap_vcf = "hapmap_3.3.hg38.vcf.gz"
hapmap_vcf_index = "hapmap_3.3.hg38.vcf.gz.tbi"
omni_vcf = "1000G_omni2.5.hg38.vcf.gz"
omni_vcf_index = "1000G_omni2.5.hg38.vcf.gz.tbi"
one_thousand_genomes_vcf = "1000G_phase1.snps.high_confidence.hg38.vcf.gz"
one_thousand_genomes_vcf_index = "1000G_phase1.snps.high_confidence.hg38.vcf.gz.tbi"
mills_vcf = "Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
mills_vcf_index = "Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi"
axiom_poly_vcf = "Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz"
axiom_poly_vcf_index = "Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz.tbi"
genome_contam_ud = "contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.UD"
genome_contam_bed = "contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.bed"
genome_contam_mu = "contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.mu"
exome_contam_ud = "contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.UD"
exome_contam_bed = "contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.bed"
exome_contam_mu = "contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.mu"