[buckets]
web_suffix = 'web'
tmp_suffix = 'tmp'
analysis_suffix = 'analysis'

[storage.rgp]
default = "https://raregen001sa.blob.core.windows.net/test"
web = "https://raregen001sa.blob.core.windows.net/test-web"
analysis = "https://raregen001sa.blob.core.windows.net/test-analysis"
tmp = "https://raregen001sa.blob.core.windows.net/test-tmp"
web_url = "https://test-web-azcpg001.azurewebsites.net/rgp"

[storage.severalgenomes]
default = "https://sevgen002sa.blob.core.windows.net/test"
web = "https://sevgen002sa.blob.core.windows.net/test-web"
analysis = "https://sevgen002sa.blob.core.windows.net/test-analysis"
tmp = "https://sevgen002sa.blob.core.windows.net/test-tmp"
web_url = "https://test-web-azcpg001.azurewebsites.net/severalgenomes"

[storage.common]
analysis = "https://sevgen002sa.blob.core.windows.net/test/common/analysis"
tmp = "https://sevgen002sa.blob.core.windows.net/test-tmp"

[workflow]
name = 'AIP'
scatter_count = 400
vcf_size_in_gb = 240  # if the input is a VCF, specify enough storage to fit it
sequencing_type = 'genome'

# optionally allow for running a different HTML script
presentation = 'cpg'

# where to register outputs, if at all
#register = 'metamist'

## override clinvar results
#clinvar_decisions = "HailTable path to private ClinVar"
#clinvar_pm5 = "HailTable path to ClinVar PM5"

[panels]
default_panel = 137
panelapp = 'https://panelapp.agha.umccr.org/api/v1/panels'
panel_month_delta = 12
require_pheno_match = ['FLG', 'GJB2']

[clinvar]
filter_benign = ['illumina laboratory services; illumina']

[moi_tests]
# thresholds for different filters during the MOI checks
gnomad_dominant = 0.001
gnomad_max_homs_dominant = 0
gnomad_max_homs_recessive = 1
gnomad_max_ac_dominant = 10
gnomad_max_hemi = 1

[csq]
# variables affecting how the VCF variants are parsed, and AnalysisVariant objects are populated
csq_string = ['allele', 'consequence', 'symbol', 'gene', 'feature', 'mane_select', 'biotype', 'exon', 'hgvsc', 'hgvsp', 'cdna_position', 'cds_position', 'amino_acids', 'protein_position', 'variant_class', 'ensp', 'lof', 'sift', 'polyphen']

[filter]
# variables for the hail operations, including CSQ sets and filter thresholds
ac_threshold = 0.01
additional_csq = ['missense_variant']
af_semi_rare = 0.01
cadd = 28.1
critical_csq = ['frameshift_variant', 'splice_acceptor_variant', 'splice_donor_variant', 'start_lost', 'stop_gained', 'stop_lost', 'transcript_ablation']
gerp = 1.0
eigen = 0.25
max_parent_ab = 0.05
minimum_depth = 10
polyphen = 0.99
revel = 0.77
sift = 0.0
spliceai = 0.5

[hail]
cancel_after_n_failures = 1
default_timeout = 6000
default_memory = 'highmem'


[references.broad]
dragmap_prefix = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/dragen_reference"
ref_fasta = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/dragen_reference/Homo_sapiens_assembly38_masked.fasta"
noalt_bed = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/sv-resources/resources/v1/primary_contigs_plus_mito.bed.gz"
genome_calling_interval_lists = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/wgs_calling_regions.hg38.interval_list"
exome_calling_interval_lists = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/exome_calling_regions.v1.interval_list"
genome_evaluation_interval_lists = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/wgs_evaluation_regions.hg38.interval_list"
exome_evaluation_interval_lists = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/exome_evaluation_regions.v1.interval_list"
genome_coverage_interval_list = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/wgs_coverage_regions.hg38.interval_list"
unpadded_intervals_file = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/hg38.even.handcurated.20k.intervals"
dbsnp_vcf = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf"
dbsnp_vcf_index = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf.idx"
hapmap_vcf = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/hapmap_3.3.hg38.vcf.gz"
hapmap_vcf_index = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/hapmap_3.3.hg38.vcf.gz.tbi"
omni_vcf = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/1000G_omni2.5.hg38.vcf.gz"
omni_vcf_index = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/1000G_omni2.5.hg38.vcf.gz.tbi"
one_thousand_genomes_vcf = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
one_thousand_genomes_vcf_index = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/1000G_phase1.snps.high_confidence.hg38.vcf.gz.tbi"
mills_vcf = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
mills_vcf_index = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi"
axiom_poly_vcf = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz"
axiom_poly_vcf_index = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz.tbi"
genome_contam_ud = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.UD"
genome_contam_bed = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.bed"
genome_contam_mu = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.mu"
exome_contam_ud = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.UD"
exome_contam_bed = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.bed"
exome_contam_mu = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.mu"
protein_coding_gtf = "https://azcpg001sa.blob.core.windows.net/reference/hg38/v0/sv-resources/resources/v1/MANE.GRCh38.v0.95.select_ensembl_genomic.gtf"

[references.gatk_sv]
wham_include_list_bed_file = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/wham_whitelist.bed"
primary_contigs_list = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/primary_contigs.list"
primary_contigs_fai = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/contig.fai"
preprocessed_intervals = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/preprocessed_intervals.interval_list"
manta_region_bed = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/primary_contigs_plus_mito.bed.gz"
melt_standard_vcf_header = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/melt_standard_vcf_header.txt"
genome_file = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/hg38.genome"
wgd_scoring_mask = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/wgd_scoring_mask.hg38.gnomad_v3.bed"
allosomal_contigs = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/allosome.fai"
contig_ploidy_priors = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/hg38.contig_ploidy_priors_homo_sapiens.tsv"
inclusion_bed = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/hg38_primary_contigs.bed"
autosome_file = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/autosome.fai"
allosome_file = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/allosome.fai"
cnmops_exclude_list = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/GRCh38_Nmask.bed"
cytoband = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/cytobands_hg38.bed.gz"
mei_bed = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/mei_hg38.bed.gz"
rmsk = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/randomForest_blacklist.withRepMask.bed.gz"
segdups = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/hg38.SD_gaps_Cen_Tel_Heter_Satellite_lumpy.blacklist.sorted.merged.bed.gz"
seed_cutoffs = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/seed_cutoff.txt"
pesr_exclude_list = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/PESR.encode.peri_all.repeats.delly.hg38.blacklist.sorted.bed.gz"
depth_exclude_list = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/depth_blacklist.sorted.bed.gz"
bin_exclude = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/bin_exclude.hg38.gatkcov.bed.gz"
empty_file = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/empty.file"
protein_coding_gtf = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/resources/v1/MANE.GRCh38.v0.95.select_ensembl_genomic.gtf"
ped_file = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v1/ped/1kg_ref_panel_v1.ped"
clean_vcf = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v1/calls/ref_panel_1kg_v1.cleaned.vcf.gz"
ref_panel_bincov_matrix = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v1/merged_evidence/ref_panel_1kg_v1.bincov.bed.gz"
qc_definitions = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v2/single_sample.qc_definitions.tsv"
contig_ploidy_model_tar = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v2/gcnv/ref_panel_1kg_v2-contig-ploidy-model.tar.gz"
model_tar_tmpl = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v2/gcnv/model_files/ref_panel_1kg_v2-gcnv-model-shard-{shard}.tar.gz"
ref_panel_PE_file_tmpl = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/ref-panel/tws_SVEvidence/pe/{sample}.pe.txt.gz"
ref_panel_SR_file_tmpl = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/ref-panel/tws_SVEvidence/sr/{sample}.sr.txt.gz"
ref_panel_SD_file_tmpl = "https://azcpg001sa.blob.core.windows.net/reference/gatk-sv/hg38/v0/sv-resources/ref-panel/tws_SVEvidence/sd/{sample}.sd.txt.gz"

[references.gnomad]
tel_and_cent_ht = "https://azcpg001sa.blob.core.windows.net/reference/gnomad/v0/telomeres_and_centromeres/hg38.telomeresAndMergedCentromeres.ht"
lcr_intervals_ht = "https://azcpg001sa.blob.core.windows.net/reference/gnomad/v0/lcr_intervals/LCRFromHengHg38.ht"
seg_dup_intervals_ht = "https://azcpg001sa.blob.core.windows.net/reference/gnomad/v0/seg_dup_intervals/GRCh38_segdups.ht"
clinvar_ht = "https://azcpg001sa.blob.core.windows.net/reference/gnomad/v0/clinvar/clinvar_20190923.ht"
hapmap_ht = "https://azcpg001sa.blob.core.windows.net/reference/gnomad/v0/hapmap/hapmap_3.3.hg38.ht"
kgp_omni_ht = "https://azcpg001sa.blob.core.windows.net/reference/gnomad/v0/kgp/1000G_omni2.5.hg38.ht"
kgp_hc_ht = "https://azcpg001sa.blob.core.windows.net/reference/gnomad/v0/kgp/1000G_phase1.snps.high_confidence.hg38.ht"
mills_ht = "https://azcpg001sa.blob.core.windows.net/reference/gnomad/v0/mills/Mills_and_1000G_gold_standard.indels.hg38.ht"
predetermined_qc_variants = "https://azcpg001sa.blob.core.windows.net/reference/gnomad/v0/sample_qc/pre_ld_pruning_qc_variants.ht"

[references.syndip]
truth_vcf = "https://azcpg001sa.blob.core.windows.net/reference/validation/syndip/full.38.20180222.vcf.gz"
regions_bed = "https://azcpg001sa.blob.core.windows.net/reference/validation/syndip/syndip.b38_20180222.bed"
truth_mt = "https://azcpg001sa.blob.core.windows.net/reference/validation/syndip/syndip.b38_20180222.mt"
regions_ht = "https://azcpg001sa.blob.core.windows.net/reference/validation/syndip/syndip_b38_20180222_hc_regions.ht"

[references.na12878]
truth_vcf = "https://azcpg001sa.blob.core.windows.net/reference/validation/na12878/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz"
regions_bed = "https://azcpg001sa.blob.core.windows.net/reference/validation/na12878/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed"
truth_mt = "https://azcpg001sa.blob.core.windows.net/reference/validation/na12878/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.mt"
regions_ht = "https://azcpg001sa.blob.core.windows.net/reference/validation/na12878/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7_hc_regions.ht"

[references]
genome_build = "GRCh38"
vep_mount = "https://azcpg001sa.blob.core.windows.net/reference/vep/105.0/mount"
liftover_38_to_37 = "https://azcpg001sa.blob.core.windows.net/reference/liftover/grch38_to_grch37.over.chain.gz"
somalier_sites = "https://azcpg001sa.blob.core.windows.net/reference/somalier/sites.hg38.vcf.gz"
seqr_combined_reference_data = "https://azcpg001sa.blob.core.windows.net/reference/seqr/v0-1/combined_reference_data_grch38.ht"
seqr_clinvar = "https://azcpg001sa.blob.core.windows.net/reference/seqr/v0-1/clinvar.GRCh38.ht"

[images]
dragmap = "azcpg001acr.azurecr.io/cpg-common/images/dragmap:1.3.0"
cpg_workflows = "azcpg001acr.azurecr.io/cpg-common/images/cpg_workflows:latest"
cpg_aip = "azcpg001acr.azurecr.io/cpg-common/images/cpg_aip:0.1.4"
bcftools = "azcpg001acr.azurecr.io/cpg-common/images/bcftools:1.16"
bedtools = "azcpg001acr.azurecr.io/cpg-common/images/bedtools:2.30.0"
cellregmap = "azcpg001acr.azurecr.io/cpg-common/images/cellregmap:0.0.3"
expansionhunter = "azcpg001acr.azurecr.io/cpg-common/images/expansionhunter:5.0.0"
fastqc = "azcpg001acr.azurecr.io/cpg-common/images/fastqc:0.11.9"
gatk = "azcpg001acr.azurecr.io/cpg-common/images/gatk:4.2.6.1"
hap-py = "azcpg001acr.azurecr.io/cpg-common/images/hap-py:0.3.15"
multipy = "azcpg001acr.azurecr.io/cpg-common/images/multipy:0.16"
multiqc = "azcpg001acr.azurecr.io/cpg-common/images/multiqc:1.13"
peer = "azcpg001acr.azurecr.io/cpg-common/images/peer:1.3"
picard = "azcpg001acr.azurecr.io/cpg-common/images/picard:2.27.4"
reviewer = "azcpg001acr.azurecr.io/cpg-common/images/reviewer:0.2.7"
samblaster = "azcpg001acr.azurecr.io/cpg-common/images/samblaster:0.1.26"
samtools = "azcpg001acr.azurecr.io/cpg-common/images/samtools:1.16.1"
somalier = "azcpg001acr.azurecr.io/cpg-common/images/somalier:0.2.15"
trtools = "azcpg001acr.azurecr.io/cpg-common/images/trtools:4.0.2"
vep = "azcpg001acr.azurecr.io/cpg-common/images/vep:105.0"
verifybamid = "azcpg001acr.azurecr.io/cpg-common/images/verifybamid:2.0.1"
stripy = "azcpg001acr.azurecr.io/cpg-common/images/stripy:2.2"

# per-cohort section
#clinvar_filter = when running a clinvar re-summary, remove submissions by these sites. Default = no removal
#cohort_panels = any panel IDs to be applied to this cohort, even if not otherwise phenotype-matched
#cohort_percentage = when generating an analysis pedigree, reduce the cohort to this percentage of the total. Default = 100
#gene_prior = if a specific gene list is to be used to determine Cat 2 (new gene-disease associations), provide the filepath here

[cohorts.acute-care]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
#cohort_percentage = 80
gene_prior = 'gs://cpg-acute-care-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.ag-hidden]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
gene_prior = 'gs://cpg-ag-hidden-test/reanalysis/pre_panelapp_mendeliome.json'
cohort_panels = [275]

[cohorts.brain-malf]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
#cohort_percentage = 80
gene_prior = 'gs://cpg-brain-malf-test/reanalysis/pre_panelapp_mendeliome.json'
cohort_panels = [3136]

[cohorts.broad-rgp]
clinvar_filter = [
    'broad institute rare disease group; broad institute',
    'laboratory for molecular medicine; mass general brigham personalized medicine'
]
gene_prior = "gs://cpg-broad-rgp-test-analysis/reanalysis/jan_2020_panels.json"

[cohorts.circa]
#cohort_percentage = 80
cohort_panels = [239]

[cohorts.epileptic-enceph]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
#cohort_percentage = 80
gene_prior = 'gs://cpg-epileptic-enceph-test/reanalysis/pre_panelapp_mendeliome.json'
cohort_panels = [202]

[cohorts.genomic-autopsy]
cohort_panels = [3763]

[cohorts.heartkids]
gene_prior = 'gs://cpg-heartkids-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.hereditary-neuro]
#cohort_percentage = 80
cohort_panels = [3120]

[cohorts.ibmdx]
cohort_panels = [56]

[cohorts.kidgen]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
gene_prior = 'gs://cpg-kidgen-test-analysis/reanalysis/pre_panelapp_mendeliome.json'
cohort_panels = [275]

[cohorts.leukodystrophies]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
cohort_panels = [298, 299, 3094]
#cohort_percentage = 80
gene_prior = 'gs://cpg-leukodystrophies-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.mito-disease]
clinvar_filter = ['victorian clinical genetics services,murdoch childrens research institute']
#cohort_percentage = 80
gene_prior = 'gs://cpg-mito-disease-test/reanalysis/pre_panelapp_mendeliome.json'
cohort_panels = [203]

[cohorts.ohmr3-mendelian]

[cohorts.ohmr4-epilepsy]
cohort_panels = [202]

[cohorts.perth-neuro]

[cohorts.ravenscroft-arch]

[cohorts.ravenscroft-rdstudy]

[cohorts.rdnow]
gene_prior = 'gs://cpg-rdnow-test/reanalysis/pre_panelapp_mendeliome.json'

[cohorts.rdp-kidney]
cohort_panels = [275]

[cohorts.rgp]

[cohorts.schr-neuro]

[cohorts.severalgenomes]

[cohorts.udn-aus]
